### ISSUE TITLE
Recipe animation - card flip

### ISSUE THREAD

**Issue by mbuchthal** [palindromed/Eat-Your-Feelings#13]

**Comment by mbuchthal** [comment]
Instead of card flip... fade in fade out?

**Comment by mbuchthal** [comment]
http://stackoverflow.com/questions/5248721/jquery-replacewith-fade-animate

**Comment by TechTakeover** [comment]
I've worked on it for awhile and haven't gotten it to work right

**Comment by mbuchthal** [comment]
Removing issue as it is not needed
